name: Scorecard Security Checks

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

permissions:
  security-events: write
  id-token: write
  contents: read

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@v2.3.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif

      - name: Save JSON report as artifact
        run: cp results.sarif scorecard-results.json

      - name: Upload JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: scorecard-json
          path: scorecard-results.json
