name: Scorecard Security Checks

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

permissions:
  security-events: write   # per pubblicare SARIF
  id-token: write
  contents: read

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true  # invia i dati a GitHub Security tab

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif

      - name: Save JSON report as artifact
        run: |
          cp results.sarif scorecard-results.json
        shell: bash

      - name: Upload JSON artifact
        uses: actions/upload-artifact@v3
        with:
          name: scorecard-json
          path: scorecard-results.json